### PR TITLE
[FLINK-35136] Bump connector version to 4.0, adapt CI workflows

### PR DESCRIPTION
**Pull request by ferenc-csaky**

### CODE REVIEW

**Comment by ferenc-csaky** [comment]
cc @MartijnVisser @snuyanzin

**Comment by JuliaBogdan** [comment]
Hi, @ferenc-csaky. I'm interested in the connector for Flink > 1.18 and glad to see this PR, thank you for the work!
I wonder if there is there anything that is blocking the release?

**Comment by ferenc-csaky** [comment]
> Hi, @ferenc-csaky. I'm interested in the connector for Flink > 1.18 and glad to see this PR, thank you for the work! I wonder if there is there anything that is blocking the release?

Hi @JuliaBogdan, unfortunately yes, it is not trivial to release the connector as is against 1.18+, because some Hadoop elements are not playing well with JDK17+, so this will be more work than I originally anticipated. I will initiate a discussion to releasethe HBase connector for Flink 1.18 and 1.19 for only JDK8 and JDK11 to at least start to bridge the current gap.

Anything that comes afterwards probably we will require to bump all Hadoop-related deps in this repo.

**Comment by JuliaBogdan** [comment]
> > Hi, @ferenc-csaky. I'm interested in the connector for Flink > 1.18 and glad to see this PR, thank you for the work! I wonder if there is there anything that is blocking the release?
> 
> Hi @JuliaBogdan, unfortunately yes, it is not trivial to release the connector as is against 1.18+, because some Hadoop elements are not playing well with JDK17+, so this will be more work than I originally anticipated. I will initiate a discussion to releasethe HBase connector for Flink 1.18 and 1.19 for only JDK8 and JDK11 to at least start to bridge the current gap.
> 
> Anything that comes afterwards probably we will require to bump all Hadoop-related deps in this repo.

I see, thanks for the quick response!
Having the connector released for JDK11 would be super useful for our use case too. Looking forward to an outcome of the discussion.

**Comment by ferenc-csaky** [comment]
@JuliaBogdan FYI started the discussion, it can be followed [here](https://lists.apache.org/thread/rsdrwv2vz2y83lco9wkxbx7l9rcbqxpv).

**Review by lvyanquan — APPROVED** [review]
LGTM.

**Comment by JuliaBogdan** [comment]
Great to see the PR merged, thanks for moving it forward @ferenc-csaky !
How does the release process and the timeline look? Is there anything I can help with to make it happen?

**Comment by ferenc-csaky** [comment]
> Great to see the PR merged, thanks for moving it forward @ferenc-csaky ! How does the release process and the timeline look? Is there anything I can help with to make it happen?

I plan to kick off the release process this week, hopefully there will be an RC by EOW. When the RC is present, anyone can help to validate it. If you are interested in that, I will post that update here as well, or you can follow the Flink dev mailing list with a [VOTE] thread about the `flink-hbase-connector` release.

**Comment by JuliaBogdan** [comment]
> > Great to see the PR merged, thanks for moving it forward @ferenc-csaky ! How does the release process and the timeline look? Is there anything I can help with to make it happen?
> 
> I plan to kick off the release process this week, hopefully there will be an RC by EOD. When the EOD is present, anyone can help to validate it. If you are interested in that, I will post that update here as well, or you can follow the Flink dev mailing list with a [VOTE] thread about the `flink-hbase-connector` release.

Sounds good! I'll follow the thread in Flink dev mailing list.

**Pull request merged**
