### PR TITLE
[FLINK-33440] Update Flink version matrix, add 1.19-SNAPSHOT to GH workflows, update flink-connector-parent

### PR DESCRIPTION
**Pull request by ferenc-csaky**
cc @MartijnVisser

### CODE REVIEW

**Comment by ferenc-csaky** [comment]
I guess we should also update the `v3.0` branch, or since there were a couple features added since that would it make sense to create a `v3.1` and release that against Flink 1.18?

**Comment by snuyanzin** [comment]
shoukd we wait a bit since currently 1.16.3 and 1.17.2 are in voting phase and then add all three?

**Comment by ferenc-csaky** [comment]
> shoukd we wait a bit since currently 1.16.3 and 1.17.2 are in voting phase and then add all three?

Yeah, that makes sense. 👍

**Comment by ferenc-csaky** [comment]
cc @MartijnVisser @snuyanzin

**Comment by snuyanzin** [comment]
There was  snappy update, probably need to add explicit dependency to cope with
https://github.com/apache/flink-connector-hbase/actions/runs/7085132836/job/19876358681?pr=35#step:14:78

**Comment by MartijnVisser** [comment]
We need to decide how to resolve the Guava dependency convergence: we can't pin the latest version, since that misses classes that are required by HBase. Perhaps we should bump HBase in general?

**Comment by ferenc-csaky** [comment]
> We need to decide how to resolve the Guava dependency convergence: we can't pin the latest version, since that misses classes that are required by HBase. Perhaps we should bump HBase in general?

Sorry for the late answer. There were already a discussion about dropping HBase 1.x back in the day before I started the externalization: https://lists.apache.org/thread/x7l2gj8g93r4v6x6953cyt6jrs8c4r1b

I am okay with dropping it, probably the sooner the better, as it would reduce the complexity of the conenctor a lot, although for 1.18.0 it is not necessary, these dep changes are required for 1.19.

@MartijnVisser @snuyanzin WDYT?

**Comment by ferenc-csaky** [comment]
@MartijnVisser pinning the older Guava also works, AFAIK externalized connectors are not necessary to depend on the `flink-shaded` Guava. I am pro removing HBase 1 though, but according to my point that may not blocks this change.

**Comment by MartijnVisser** [comment]
@ferenc-csaky Will you rebase this PR? I'll close https://github.com/apache/flink-connector-hbase/pull/39

**Comment by ferenc-csaky** [comment]
> @ferenc-csaky Will you rebase this PR? I'll close #39

Yes, will do.

**Comment by ferenc-csaky** [comment]
@MartijnVisser updated the version matrix, PTAL.

Removed the 1.18.0 run for the `v3.0` branch, as it was not released for Flink 1.18. My understanding is that would require a `v3.1`, right?

**Comment by ferenc-csaky** [comment]
@snuyanzin I fixed the dep convergence for 1.19 the last CI run failed on, also had to change `HBaseTablePlanTest` as the JUnit5 migration for `TableTestBase` in the core repo in 1.19 required some adaptation. Can you retrigger another run pls?

**Review by snuyanzin — APPROVED** [review]

**Pull request merged**
