### PR TITLE
[FLINK-30386] Fix the issue that column constraint lacks primary key …

### PR DESCRIPTION
**Pull request by ferenc-csaky**
…not enforced check

This closes #21507

### CODE REVIEW

**Comment by ferenc-csaky** [comment]
@MartijnVisser now the 1.17 runs are failing because of license changes, and the 1.16 runs because of the E2E tests, so this could be merged I think.

**Comment by MartijnVisser** [comment]
> the 1.17 runs are failing because of license changes, and the 1.16 runs because of the E2E tests, so this could be merged I think.

It looks like both failed because of licensing issues. Do we already have a separate ticket for this?

**Comment by ferenc-csaky** [comment]
> > the 1.17 runs are failing because of license changes, and the 1.16 runs because of the E2E tests, so this could be merged I think.
> 
> It looks like both failed because of licensing issues. Do we already have a separate ticket for this?

Oh yes, that's right, now the E2E tets actually ran, I just assumed they failed cause I saw them failing before. No there is no jira yet. If you create one, feel free to assign it to me, I'll take a look later today.

**Comment by ferenc-csaky** [comment]
@MartijnVisser added a commit, without a Jira tag for now, but if it should has a separate ticket I'll create one, I just felt this might be a "hotfix" type of change, as this is caused by the E2E tests, cause I changed the actually included deps there and missed the licensing part.

**Review by MartijnVisser — APPROVED** [review]

**Pull request merged**
