### PR TITLE
[FLINK-30360][Connectors/HBase] When specified the partial columns, ignore all empty columns

### PR DESCRIPTION
**Pull request by wjc920**

### CODE REVIEW

**Comment by wjc920** [comment]
@MartijnVisser I recreate a pr at here.

**Review by ferenc-csaky — APPROVED** [review]
LGTM!

**Comment by wjc920** [comment]
@ferenc-csaky  Could you merge this PR?

**Comment by wjc920** [comment]
@MartijnVisser Could you merge this PR?

**Comment by MartijnVisser** [comment]
@wjc920 I misread, since the HBase connector isn't externalized yet, it doesn't make sense to merge this. I'll revert the change.

**Pull request merged**
